### PR TITLE
Frontend: Comment Component Implementation

### PR DESCRIPTION
**Pull request by iggyray**
Changes:
Backend:

- debugged `commentRepository`

Frontend:

- Created `Comment` component
- Created `CommentBoard` component
- Hooked frontend to backend endpoints

TODO:

- Styling of `CommentBoard`
- Refactor backend to save `user_name` when comment is added

Screenshot 2023-05-28 at 1 37 57 AM

### CODE REVIEW

**Comment by tonklable** [comment]
Are you going to display the name instead of user ID in the next pr?

**Comment by tonklable** [comment]
image

I'm not sure why I got error from these two functions? Where are these from? But overall it seems work.

**Comment by iggyray** [comment]
> 

Thats strange, can you find them in `handler.go`? @tonklable

**Comment by tonklable** [comment]
Just fount it OK, How about the name?

**Pull request merged**
